In [1]:
# import pandas library
import pandas as pd

Read the CSV

In [32]:
kiva_data = pd.read_csv('./kiva_loans.csv')
print(f'Number of entries: {kiva_data.shape[0]:,}\n'
      f'Number of features: {kiva_data.shape[1]:,}\n\n')

Number of entries: 671,205
Number of features: 20

In [33]:
kiva_data.head()

,id,funded_amount,loan_amount,activity,sector,use,country_code,country,region,currency,partner_id,posted_time,disbursed_time,funded_time,term_in_months,lender_count,tags,borrower_genders,repayment_interval,date
0,653051,300.0,300.0,Fruits & Vegetables,Food,"To buy seasonal, fresh fruits to sell.",PK,Pakistan,Lahore,PKR,247.0,2014-01-01 06:12:39+00:00,2013-12-17 08:00:00+00:00,2014-01-02 10:06:32+00:00,12.0,12,NaN,female,irregular,2014-01-01
1,653053,575.0,575.0,Rickshaw,Transportation,to repair and maintain the auto rickshaw used ...,PK,Pakistan,Lahore,PKR,247.0,2014-01-01 06:51:08+00:00,2013-12-17 08:00:00+00:00,2014-01-02 09:17:23+00:00,11.0,14,NaN,"female, female",irregular,2014-01-01
2,653068,150.0,150.0,Transportation,Transportation,To repair their old cycle-van and buy another ...,IN,India,Maynaguri,INR,334.0,2014-01-01 09:58:07+00:00,2013-12-17 08:00:00+00:00,2014-01-01 16:01:36+00:00,43.0,6,"user_favorite, user_favorite",female,bullet,2014-01-01
3,653063,200.0,200.0,Embroidery,Arts,to purchase an embroidery machine and a variet...,PK,Pakistan,Lahore,PKR,247.0,2014-01-01 08:03:11+00:00,2013-12-24 08:00:00+00:00,2014-01-01 13:00:00+00:00,11.0,8,NaN,female,irregular,2014-01-01
4,653084,400.0,400.0,Milk Sales,Food,to purchase one buffalo.,PK,Pakistan,Abdul Hakeem,PKR,245.0,2014-01-01 11:53:19+00:00,2013-12-17 08:00:00+00:00,2014-01-01 19:18:51+00:00,14.0,16,NaN,female,monthly,2014-01-01

In [11]:
#get list of countries
country_list = kiva_data['country'].unique().tolist()

country_list

['Pakistan',
 'India',
 'Kenya',
 'Nicaragua',
 'El Salvador',
 'Tanzania',
 'Philippines',
 'Peru',
 'Senegal',
 'Cambodia',
 'Liberia',
 'Vietnam',
 'Iraq',
 'Honduras',
 'Palestine',
 'Mongolia',
 'United States',
 'Mali',
 'Colombia',
 'Tajikistan',
 'Guatemala',
 'Ecuador',
 'Bolivia',
 'Yemen',
 'Ghana',
 'Sierra Leone',
 'Haiti',
 'Chile',
 'Jordan',
 'Uganda',
 'Burundi',
 'Burkina Faso',
 'Timor-Leste',
 'Indonesia',
 'Georgia',
 'Ukraine',
 'Kosovo',
 'Albania',
 'The Democratic Republic of the Congo',
 'Costa Rica',
 'Somalia',
 'Zimbabwe',
 'Cameroon',
 'Turkey',
 'Azerbaijan',
 'Dominican Republic',
 'Brazil',
 'Mexico',
 'Kyrgyzstan',
 'Armenia',
 'Paraguay',
 'Lebanon',
 'Samoa',
 'Israel',
 'Rwanda',
 'Zambia',
 'Nepal',
 'Congo',
 'Mozambique',
 'South Africa',
 'Togo',
 'Benin',
 'Belize',
 'Suriname',
 'Thailand',
 'Nigeria',
 'Mauritania',
 'Vanuatu',
 'Panama',
 'Virgin Islands',
 'Saint Vincent and the Grenadines',
 "Lao People's Democratic Republic",
 'Malawi',
 'Myanmar (Burma)',
 'Moldova',
 'South Sudan',
 'Solomon Islands',
 'China',
 'Egypt',
 'Guam',
 'Afghanistan',
 'Madagascar',
 'Namibia',
 'Puerto Rico',
 'Lesotho',
 "Cote D'Ivoire",
 'Bhutan']

In [30]:
#get list of activities
activity_list = kiva_data['activity'].unique().tolist()

activity_list

['Fruits & Vegetables',
 'Rickshaw',
 'Transportation',
 'Embroidery',
 'Milk Sales',
 'Services',
 'Dairy',
 'Beauty Salon',
 'Manufacturing',
 'Food Production/Sales',
 'Wholesale',
 'General Store',
 'Clothing Sales',
 'Poultry',
 'Tailoring',
 'Sewing',
 'Bakery',
 'Restaurant',
 'Food Stall',
 'Farming',
 'Construction Supplies',
 'Personal Products Sales',
 'Home Products Sales',
 'Natural Medicines',
 'Fish Selling',
 'Education provider',
 'Shoe Sales',
 'Machinery Rental',
 'Butcher Shop',
 'Pigs',
 'Personal Expenses',
 'Food Market',
 'Cosmetics Sales',
 'Personal Housing Expenses',
 'Retail',
 'Energy',
 'Grocery Store',
 'Construction',
 'Agriculture',
 'Motorcycle Transport',
 'Charcoal Sales',
 'Food',
 'Pharmacy',
 'Fishing',
 'Timber Sales',
 'Cattle',
 'Electronics Repair',
 'Electronics Sales',
 'Vehicle',
 'Cafe',
 'Blacksmith',
 'Higher education costs',
 'Used Clothing',
 'Fuel/Firewood',
 'Upholstery',
 'Catering',
 'Animal Sales',
 'Cereals',
 'Vehicle Repairs',
 'Arts',
 'Cloth & Dressmaking Supplies',
 'Mobile Phones',
 'Spare Parts',
 'Clothing',
 'Metal Shop',
 'Barber Shop',
 'Furniture Making',
 'Crafts',
 'Home Energy',
 'Home Appliances',
 'Wedding Expenses',
 'Taxi',
 'Secretarial Services',
 'Livestock',
 'Property',
 'Recycling',
 'Farm Supplies',
 'Auto Repair',
 'Beverages',
 'Plastics Sales',
 'Electrical Goods',
 'Carpentry',
 'Photography',
 'Jewelry',
 'Bricks',
 'Pub',
 'Phone Use Sales',
 'Water Distribution',
 'Paper Sales',
 'Computers',
 'Liquor Store / Off-License',
 'Utilities',
 'Knitting',
 'Weaving',
 'Party Supplies',
 'Medical Clinic',
 'Internet Cafe',
 'Consumer Goods',
 'Cement',
 'Electrician',
 'Primary/secondary school costs',
 'Veterinary Sales',
 'Land Rental',
 'Laundry',
 'Call Center',
 'Perfumes',
 'Hotel',
 'Motorcycle Repair',
 'Movie Tapes & DVDs',
 'Quarrying',
 'Personal Medical Expenses',
 'Bookstore',
 'Decorations Sales',
 'Recycled Materials',
 'Office Supplies',
 'Souvenir Sales',
 'Renewable Energy Products',
 'Health',
 'Printing',
 'Phone Repair',
 'Traveling Sales',
 'Flowers',
 'Bicycle Repair',
 'Entertainment',
 'Phone Accessories',
 'Hardware',
 'Used Shoes',
 'Music Discs & Tapes',
 'Games',
 'Balut-Making',
 'Textiles',
 'Child Care',
 'Goods Distribution',
 'Florist',
 'Cobbler',
 'Dental',
 'Bookbinding',
 'Cheese Making',
 'Bicycle Sales',
 'Well digging',
 'Technology',
 'Musical Performance',
 'Waste Management',
 'Film',
 'Tourism',
 'Musical Instruments',
 'Religious Articles',
 'Machine Shop',
 'Cleaning Services',
 'Sporting Good Sales',
 'Patchwork',
 'Funerals',
 'Air Conditioning',
 'Communications',
 'Adult Care',
 'Landscaping / Gardening',
 'Aquaculture']

In [ ]:
# Select rows where the country is either 'Kenya' or 'El Salvador'
kenya_or_elsalvador = kiva_data[kiva_data.country.isin(['Kenya', 'El Salvador'])]
print(f'{kenya_or_elsalvador.shape[0]:,} rows where country is Kenya or El Salvador')

# Select rows where the loan amount is greater than 3000
loan_amount_gt_1000 = kiva_data[kiva_data.loan_amount > 3000]
print(f'{loan_amount_gt_1000.shape[0]:,} rows where loan amount is greater than 3000')

# Select rows where the country is 'Kenya' and the loan amount is greater than 3000
pakistan_and_loan_amount_gt_1000 = kiva_data[(kiva_data.country == 'Pakistan') & (kiva_data.loan_amount > 3000)]
print(f'{pakistan_and_loan_amount_gt_1000.shape[0]:,} rows where country is Kenya and loan amount is greater than 3000')

32,753 rows where country is Kenya or El Salvador
7,442 rows where loan amount is greater than 1000
5 rows where country is Kenya and loan amount is greater than 1000

Sort the table by activity:

In [34]:
# Sort table using one or more columns
kiva_data.sort_values(by='activity', ascending=True)

,id,funded_amount,loan_amount,activity,sector,use,country_code,country,region,currency,partner_id,posted_time,disbursed_time,funded_time,term_in_months,lender_count,tags,borrower_genders,repayment_interval,date
50683,703128,1825.0,1825.0,Adult Care,Services,to make improvements to her business as requir...,CO,Colombia,Medellín,COP,177.0,2014-04-27 02:22:23+00:00,2014-03-27 07:00:00+00:00,2014-05-11 02:48:21+00:00,27.0,65,"volunteer_pick, volunteer_like, #Elderly, #Hea...",female,monthly,2014-04-27
650736,1313451,1550.0,1550.0,Adult Care,Services,to buy new equipment for her adult care business.,LB,Lebanon,Beirut,LBP,404.0,2017-06-05 09:42:34+00:00,2017-05-26 07:00:00+00:00,2017-06-13 17:31:49+00:00,18.0,38,"#Single, #Health and Sanitation, #Female Educa...",female,monthly,2017-06-05
407985,1055219,350.0,350.0,Agriculture,Agriculture,to buy agricultural inputs and rice seeds to g...,CO,Colombia,Tierralta,COP,177.0,2016-04-15 21:58:03+00:00,2016-03-16 07:00:00+00:00,2016-04-28 12:37:19+00:00,14.0,14,"#Animals, #Parent",male,bullet,2016-04-15
360376,1006837,675.0,675.0,Agriculture,Agriculture,to purchase a solar light and gain access to c...,KE,Kenya,Webuye,KES,202.0,2016-01-12 07:09:28+00:00,2016-02-01 08:00:00+00:00,2016-01-18 20:41:53+00:00,11.0,7,"#Sustainable Ag, #Vegan, #Eco-friendly, #Techn...","female, female, female, male, female, male, ma...",bullet,2016-01-12
575111,1236003,1450.0,1450.0,Agriculture,Agriculture,"to buy a cow, potato seedlings, fertilizer, an...",AM,Armenia,Gegharkunik region,AMD,146.0,2017-02-10 11:10:16+00:00,2017-02-08 08:00:00+00:00,2017-03-08 22:16:39+00:00,26.0,35,"#Animals, #Parent",female,monthly,2017-02-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390517,1037119,550.0,550.0,Wholesale,Wholesale,to buy harvested rice,PH,Philippines,"San Dionisio, Iloilo",PHP,125.0,2016-03-11 09:23:14+00:00,2016-02-12 08:00:00+00:00,2016-03-20 03:14:34+00:00,12.0,16,"#Elderly, user_favorite, #Vegan",male,irregular,2016-03-11
257482,904691,325.0,325.0,Wholesale,Wholesale,to buy milk from smallholder dairy farmers to ...,KE,Kenya,Nandi Hills,KES,156.0,2015-06-19 09:47:09+00:00,2015-06-12 07:00:00+00:00,2015-06-23 14:48:15+00:00,14.0,13,"#Single Parent, #Woman Owned Biz",female,monthly,2015-06-19
617094,1279042,1675.0,1675.0,Wholesale,Wholesale,to buy pesticides for his wholesale business a...,UG,Uganda,Rukungiri,UGX,222.0,2017-04-13 13:53:42+00:00,2017-03-14 07:00:00+00:00,2017-04-28 20:55:11+00:00,7.0,59,"#Parent, #Parent, user_favorite, user_favorite...","male, male, male, male, male, male, female, ma...",monthly,2017-04-13
341024,987661,2000.0,2000.0,Wholesale,Wholesale,to start a beauty products wholesale trade in ...,LB,Lebanon,Qana,USD,77.0,2015-11-30 10:52:04+00:00,2015-11-25 08:00:00+00:00,2015-12-19 11:19:17+00:00,20.0,73,#Woman Owned Biz,female,monthly,2015-11-30
161466,810347,1975.0,1975.0,Wholesale,Wholesale,to purchase oil and ghee for his shop.,PK,Pakistan,Karachi,PKR,247.0,2014-12-04 07:05:44+00:00,2014-12-23 08:00:00+00:00,2014-12-25 01:42:39+00:00,13.0,68,"#Parent, #Post-disbursed, #Elderly",male,monthly,2014-12-04

Look at the mean loan amount per activity:

In [35]:
# Group and aggregate rows with "groupby"
kiva_data.groupby('activity').agg({'loan_amount': 'mean'})

                    loan_amount
activity
Adult Care          1687.500000
Agriculture         1015.462754
Air Conditioning    1225.694444
Animal Sales        1137.030421
Aquaculture          762.268519
...                         ...
Water Distribution  1205.673759
Weaving              743.186424
Wedding Expenses     964.938272
Well digging        1221.428571
Wholesale           1323.879552

[163 rows x 1 columns]

And by country:

In [12]:
# Group and aggregate rows with "groupby"
kiva_data.groupby('country').agg({'loan_amount': 'mean'})

                loan_amount
country
Afghanistan     6000.000000
Albania         1520.673077
Armenia         1668.637532
Azerbaijan      1702.760417
Belize          1014.705882
...                     ...
Vietnam         1311.237330
Virgin Islands  5000.000000
Yemen            859.652318
Zambia          1291.666667
Zimbabwe         629.891304

[81 rows x 1 columns]

Use apply by:

In [36]:
# Create a new variable using apply and lambda function
kiva_data['term_in_years'] = kiva_data['term_in_months'].apply(lambda x: x/12)
kiva_data.head()

,id,funded_amount,loan_amount,activity,sector,use,country_code,country,region,currency,...,posted_time,disbursed_time,funded_time,term_in_months,lender_count,tags,borrower_genders,repayment_interval,date,term_in_years
0,653051,300.0,300.0,Fruits & Vegetables,Food,"To buy seasonal, fresh fruits to sell.",PK,Pakistan,Lahore,PKR,...,2014-01-01 06:12:39+00:00,2013-12-17 08:00:00+00:00,2014-01-02 10:06:32+00:00,12.0,12,NaN,female,irregular,2014-01-01,1.000000
1,653053,575.0,575.0,Rickshaw,Transportation,to repair and maintain the auto rickshaw used ...,PK,Pakistan,Lahore,PKR,...,2014-01-01 06:51:08+00:00,2013-12-17 08:00:00+00:00,2014-01-02 09:17:23+00:00,11.0,14,NaN,"female, female",irregular,2014-01-01,0.916667
2,653068,150.0,150.0,Transportation,Transportation,To repair their old cycle-van and buy another ...,IN,India,Maynaguri,INR,...,2014-01-01 09:58:07+00:00,2013-12-17 08:00:00+00:00,2014-01-01 16:01:36+00:00,43.0,6,"user_favorite, user_favorite",female,bullet,2014-01-01,3.583333
3,653063,200.0,200.0,Embroidery,Arts,to purchase an embroidery machine and a variet...,PK,Pakistan,Lahore,PKR,...,2014-01-01 08:03:11+00:00,2013-12-24 08:00:00+00:00,2014-01-01 13:00:00+00:00,11.0,8,NaN,female,irregular,2014-01-01,0.916667
4,653084,400.0,400.0,Milk Sales,Food,to purchase one buffalo.,PK,Pakistan,Abdul Hakeem,PKR,...,2014-01-01 11:53:19+00:00,2013-12-17 08:00:00+00:00,2014-01-01 19:18:51+00:00,14.0,16,NaN,female,monthly,2014-01-01,1.166667

Find loan to value percent per activity

In [37]:
# Calculate the mean of funded_amount for each activity
funded_amount_mean_per_activity = kiva_data.groupby('activity')['funded_amount'].mean()

# Calculate the mean of loan_amount for each activity
loan_amount_mean_per_activity = kiva_data.groupby('activity')['loan_amount'].mean()

# Subtract the mean funded_amount from the mean loan_amount for each activity
loan_to_value_per_activity = funded_amount_mean_per_activity/loan_amount_mean_per_activity*100

loan_to_value_per_activity = loan_to_value_per_activity.rename('loan_to_value %')
loan_to_value_per_activity

activity
Adult Care            100.000000
Agriculture            93.039155
Air Conditioning       93.144476
Animal Sales           94.979886
Aquaculture            86.607956
                         ...
Water Distribution     92.209559
Weaving                99.247924
Wedding Expenses       82.906858
Well digging          100.000000
Wholesale              96.535308
Name: loan_to_value %, Length: 163, dtype: float64